# Generated by Django 5.2.17 on 2026-09-14 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photograph',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('camera_gear', models.CharField(max_length=255)),
                ('capture_settings', models.CharField(max_length=255)),
                ('editing_software', models.CharField(choices=[('lightroom', 'Adobe Lightroom'), ('photoshop', 'Adobe Photoshop'), ('capture-one', 'Capture One'), ('none', 'Tanpa Editing / Straight Out of Camera')], default='lightroom', max_length=20)),
                ('location_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('taken_at', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-taken_at', '-uploaded_at'],
            },
        ),
    ]